FULL_SIZE = "full_size"
START = 0

# Colors
BLUE = 'BLUE'
CYAN = 'CYAN'
GREEN = 'GREEN'
RED = 'RED'
BLACK = 'BLACK'
WHITE = 'WHITE'
YELLOW = 'YELLOW'
MAGENTA = 'MAGENTA'

# Background Colors
BLACK_BG = 'BLACK'
RED_BG = 'RED'
GREEN_BG = 'GREEN'
YELLOW_BG = 'YELLOW'
BLUE_BG = 'BLUE'
CYAN_BG = 'CYAN'
WHITE_BG = 'WHITE'
MAGENTA_BG = 'MAGENTA'
