class IndexStartOutOfBoundError(Exception):
    def __init__(self) -> None: ...

class StringNotCallable(Exception):
    def __init__(self) -> None: ...

class ColorNotFoundError(Exception):
    def __init__(self, color: str) -> None: ...

class BackgroundColorNotFound(Exception):
    def __init__(self, color: str) -> None: ...

class CannotConvertToError(Exception):
    def __init__(self) -> None: ...
